baseurl = "https://royqh1979.github.com/redpandacpp/" 
title = "Red Panda C++"
theme = "hugo-universal-theme-custom"
themesDir = "themes/"
languageCode = "en"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Documents"
    identifier = "menu.documents"
    url        = "/img/template-homepage.png"
    weight    = 2

[[menu.main]]
    name       = "Tutorials"
    identifier = "section.tutorials"
    url        = ""
    weight     = 1
    parent     = "menu.documents"
    post       = 1

[[menu.main]]
    name       = "Introduction Tutorials"
    url        = "/blog/2022/02/05/basictutorial/"
    weight     = 1
    parent     = "section.tutorials"

[[menu.main]]
    name       = "Usages"
    identifier = "section.usages"
    url        = ""
    weight     = 1
    parent     = "menu.documents"
    post       = 2

[[menu.main]]
    name       = "Debug"
    url        = "/blog/2022/02/04/debug/"
    weight     = 1
    parent     = "section.usages"

[[menu.main]]
    name       = "Problem Set & OJ"
    url        = "/blog/2022/02/04/problemset/"
    weight     = 2
    parent     = "section.usages"


[[menu.main]]
    name       = "Download"
    identifier = "menu.download"
    url        = "/download/"
    weight     = 3

[[menu.main]]
    name       = "Blogs"
    identifier = "menu.blogs"
    url        = "/blog/"
    weight     = 4

[[menu.main]]
    name       = "Support"
    identifier = "menu.support"
    url        = "/support/"
    weight     = 5

[[menu.main]]
    name       = "Contributors"
    identifier = "menu.contributors"
    url        = "/contributors/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/royqh1979/RedPanda-CPP"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Gitee"
    url = "https://gitee.com/royqh1979/RedPanda-CPP"
    pre = "<i class='fab fa-2x fa-git-alt'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Roy Qu (royqh1979@gmail.com)"
    defaultKeywords = ["C", "C++", "IDE", "dev-c++"]
    mainSections = ["blog"]
    defaultDescription = "跨平台的轻量级开源C/C++ IDE"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = ""

    latitude = "0"
    longitude = "0"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    # formspree_action = ""
    # contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    # enableRecaptchaInContactForm = false
    # googleRecaptchaKey = ""

    # about_us = ""
    copyright = "Copyright (c) 2021 - 2022, Roy Qu (royqh1979@gmail.com); all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "Red Panda C++"

    logo = "img/logo.svg"
#    logo_small = "img/logo-small.png"


[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Blogs"
    # subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = true

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
